# Generated by Django 4.2.7 on 2025-11-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_cost',
            new_name='delivery_charge',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_city',
            new_name='detected_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_country',
            new_name='detected_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_state',
            new_name='detected_region',
        ),
        migrations.RemoveField(
            model_name='incompleteorder',
            name='cart_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='cart_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='delivery_area',
            field=models.CharField(choices=[('inside_dhaka', 'ঢাকা সিটির ভেতরে'), ('outside_dhaka', 'ঢাকা সিটির বাইরে')], default='inside_dhaka', max_length=20),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='detected_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='detected_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='detected_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='encrypted_cart_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incompleteorder',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(choices=[('inside_dhaka', 'ঢাকা সিটির ভেতরে'), ('outside_dhaka', 'ঢাকা সিটির বাইরে')], default='inside_dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=20),
        ),
    ]
